loop 2 arrays

diff --git a/.github/actions/validate-output/action.yml b/.github/actions/validate-output/action.yml
--- a/.github/actions/validate-output/action.yml
+++ b/.github/actions/validate-output/action.yml
@@ -32,6 +32,20 @@ runs:
     - name: Validate relevant-files output
       shell: "bash"
       run: |
+        validate_file_list () {
+          actual=$1
+          expected=$2
+
+          actual_sorted=$(echo "$actual" | jq 'split(",") | sort_by(.) | join(",")')
+          expected_sorted=$(echo "$expected" | jq 'split(",") | sort_by(.) | join(",")')
+
+          if [ $actual_sorted != $expected_sorted ]
+          then
+            echo "::error::Not expected result, expected: ${expected_sorted}, actual ${actual_sorted}"
+            exit 1
+          fi
+        }
+
         json_actual_str=$(echo '${{ inputs.relevant-files-actual }}')
         json_expected_str=$(echo '${{ inputs.relevant-files-actual }}')
         is_array=$(echo "$json_actual_str" | jq --raw-output 'if type=="array" then "yes" else "no" end')
@@ -40,18 +54,14 @@ runs:
 
         if [ "$is_array" = "no" ]
         then
-          actual_sorted=$(echo "$json_actual_str" | jq 'split(",") | sort_by(.) | join(",")')
-          expected_sorted=$(echo "$json_expected_str" | jq 'split(",") | sort_by(.) | join(",")')
-
-          if [ $actual_sorted != $expected_sorted ]
-          then
-            echo "::error::Not expected result, expected: ${expected_sorted}, actual ${actual_sorted}"
-            exit 1
-          fi
+          validate_file_list $json_actual_str $json_expected_str
         else
           echo "we have an array"
 
-          echo "$json_actual_str" | jq -c '.[]' | while read i; do
-            echo "$i"
+          actual_arr=${echo "$json_actual_str" | jq -c '.[]'}
+          expected_arr=${echo "$json_expected_str" | jq -c '.[]'}
+
+          for i in "${!expected_arr[@]}"; do
+            printf "%s is in %s\n" "${expected_arr[i]}" "${actual_arr[i]}"
           done
         fi
