feat: add multi-is-relevant test (#2)
* feat: add multi-is-relevant test

* detect config

* syntax fix

* fix var name

* parse and loop

* fix test json formatting

* [feature/multi-is-relevant] fix json

* better debug

* use get with default

* creates isRelevant function

* syntax

* run isRelevant on config

* fix bug

* fix debug

* improve test

* new test case

* fix debug

* output results list if config passed

* try PurePath match

* fix bug

* improve test

* debug added

* more debug

* debug

* improve test

* fix tests

* fix tests

* more debug

* better debug

* better debug

* fix test

* try posix

* fiddle with test

* try pathspec

* pip

* revert

* debug

* more debug

* debug

* debug

* fix

* fix

* tweak

* negative test case added

* better globbing

* debug

* debug

* tweak

* tweak

* fix

* do dumps

* complex expectations

* make results jsonish

* res type check

* tweak

* tweak

* use raw

* do some array stuff

* fix syntax

* loop 2 arrays

* syntax fix

* improve

* make proper array

* validate array items match

* try again

* try try again

* check all good when order different

* better logs

* better logs

* fix syntax

* better array validation

* better test

* fix

* fix

* break tests to test tests

* unbreak tests

diff --git a/.github/actions/validate-output/action.yml b/.github/actions/validate-output/action.yml
--- a/.github/actions/validate-output/action.yml
+++ b/.github/actions/validate-output/action.yml
@@ -22,21 +22,85 @@ runs:
     - name: Validate relevant output
       shell: "bash"
       run: |
-        actual="${{ inputs.relevant-actual }}"
-        expected="${{ inputs.relevant-expected }}"
-        if [ $actual != $expected ]
+        json_actual_str='${{ inputs.relevant-actual }}'
+        json_expected_str='${{ inputs.relevant-expected }}'
+
+        is_array=$(echo "$json_expected_str" | jq --raw-output 'if type=="array" then "yes" else "no" end')
+
+        echo "Expected an array? $is_array"
+
+        if [ "$is_array" = "no" ]
         then
-          echo "::error::Not expected result, expected '${expected}', actual '${actual}'"
-          exit 1
+          if [ $json_actual_str != $json_expected_str ]
+          then
+            echo "::error::Not expected result, expected '${expected}', actual '${actual}'"
+            exit 1
+          fi
+        else
+          readarray -t actual_arr < <(echo "$json_actual_str" | jq -c '.[]')
+          readarray -t expected_arr < <(echo "$json_expected_str" | jq -c '.[]')
+
+          if [ "${#actual_arr[@]}" -ne "${#expected_arr[@]}" ]; then
+            echo "::error::Expected ${#expected_arr[@]} items in array but found ${#actual_arr[@]}"
+            exit 1
+          fi
+
+          for i in "${!expected_arr[@]}"; do
+            printf "expected: %s, actual: %s\n" "${expected_arr[i]}" "${actual_arr[i]}"
+
+            if [ "${actual_arr[i]}" != "${expected_arr[i]}" ]
+            then
+              echo "::error::Not expected result, expected '${expected_arr[i]}', actual '${actual_arr[i]}'"
+              exit 1
+            fi
+
+            echo "✓"
+          done
         fi
     - name: Validate relevant-files output
       shell: "bash"
       run: |
-        actual_sorted=$(echo '"${{ inputs.relevant-files-actual }}"' | jq 'split(",") | sort_by(.) | join(",")')
-        expected_sorted=$(echo '"${{ inputs.relevant-files-expected }}"' | jq 'split(",") | sort_by(.) | join(",")')
+        validate_file_list () {
+          actual=$1
+          expected=$2
 
-        if [ $actual_sorted != $expected_sorted ]
+          actual_sorted=$(echo "$actual" | jq 'split(",") | sort_by(.) | join(",")')
+          expected_sorted=$(echo "$expected" | jq 'split(",") | sort_by(.) | join(",")')
+
+          if [ $actual_sorted != $expected_sorted ]
+          then
+            echo "::error::Not expected result, expected: ${expected_sorted}, actual ${actual_sorted}"
+            exit 1
+          else
+            echo "actual sorted: $actual_sorted"
+            echo "EQUALS"
+            echo "expected sorted: $expected_sorted"
+          fi
+        }
+
+        json_actual_str=$(echo '${{ inputs.relevant-files-actual }}')
+        json_expected_str=$(echo '${{ inputs.relevant-files-expected }}')
+        is_array=$(echo "$json_expected_str" | jq --raw-output 'if type=="array" then "yes" else "no" end')
+
+        echo "Expected an array? $is_array"
+
+        if [ "$is_array" = "no" ]
         then
-          echo "::error::Not expected result, expected: ${expected_sorted}, actual ${actual_sorted}"
-          exit 1
+          validate_file_list $json_actual_str $json_expected_str
+        else
+          echo "Checking arrays are comparable..."
+
+          readarray -t actual_arr < <(echo "$json_actual_str" | jq -c '.[]')
+          readarray -t expected_arr < <(echo "$json_expected_str" | jq -c '.[]')
+
+          if [ "${#actual_arr[@]}" -ne "${#expected_arr[@]}" ]; then
+            echo "::error::Expected ${#expected_arr[@]} items in array but found ${#actual_arr[@]}"
+            exit 1
+          fi
+
+          for i in "${!expected_arr[@]}"; do
+            printf "expected: %s, actual: %s\n" "${expected_arr[i]}" "${actual_arr[i]}"
+            validate_file_list "${expected_arr[i]}" "${actual_arr[i]}"
+            echo "✓"
+          done
         fi
